name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oras-project/setup-oras@v1
      - run: bash bootstrap.sh
      - run: bash scripts/validate-catalog-repo.sh
